#!/bin/bash
# Script de deploy — Swiftpay
# Requisitos: Vercel CLI + Railway CLI

echo "=============================================="
echo "  Swiftpay — Deploy para Producao"
echo "=============================================="
echo ""
echo "Passo 1: Vercel — Admin Dashboard"
echo "  cd web && npx vercel --prod"
echo "  Variavel: NEXT_PUBLIC_API_URL=https://api-gestao.railway.app/api/v1"
echo ""
echo "Passo 2: Vercel — Checkout"
echo "  cd checkout && npx vercel --prod"
echo "  Variavel: NEXT_PUBLIC_API_URL=https://api-payment.railway.app/api/v1"
echo ""
echo "Passo 3: Railway — Gestao API"
echo "  railway service create gestao-api"
echo "  railway environment GESTAO_DB_CONNECTION"
echo "  railway up --service gestao-api"
echo ""
echo "Passo 4: Railway — Payment API"
echo "  railway service create payment-api"
echo "  railway up --service payment-api"
echo ""
echo "Passo 5: Railway — PostgreSQL"
echo "  railway add postgresql"
echo ""
echo "=============================================="
echo ""
echo "VARIAVEIS DE AMBIENTE (obrigatorias):"
echo "----------------------------------------------"
echo "  MagicPay__ApiKey=geRBOFqMK7ZCrVmpqhUGuJjq8nqQzrSIrZVIJYVXRFE"
echo "  Jwt__Secret=<GERAR_UMA_SECRET_FORTE>"
echo "  ConnectionStrings__DefaultConnection=<RAILWAY_DB_URL>"
echo "  Redis__ConnectionString=<RAILWAY_REDIS_URL>"
echo "  ConnectionStrings__RabbitMQ=<RAILWAY_RABBITMQ_URL>"
echo ""
echo "=============================================="
