overrides:
  "@internationalized/date": "3.12.3"
allowBuilds:
  '@firebase/util': set this to true or false
  '@tsparticles/engine': set this to true or false
  protobufjs: set this to true or false
  puppeteer: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
