apiVersion: 1

datasources:
  # PostgreSQL - Banco Principal (Payments, Merchants, Users)
  - name: PostgreSQL-Primary
    type: postgres
    access: proxy
    url: swiftpaydb:5432
    database: swiftpay
    user: swiftpayuser
    editable: false
    secureJsonData:
      password: swiftpaypassword
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400

  # PostgreSQL - Banco de Logs
  - name: PostgreSQL-Logs
    type: postgres
    access: proxy
    url: swiftpaylogsdb:5432
    database: swiftpaylogs
    user: logsuser
    editable: false
    secureJsonData:
      password: logspassword
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
