<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable> 
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>safefy_api_payment</RootNamespace>
    <AssemblyName>safefy-api-payment</AssemblyName>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>

  <!-- Excluir pasta Tests do projeto principal -->
  <ItemGroup>
    <Compile Remove="Tests\**" />
    <Content Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup Condition="Exists('..\swiftpay-api-core\swiftpay-api-core.csproj')">
    <ProjectReference Include="..\swiftpay-api-core\swiftpay-api-core.csproj" />
  </ItemGroup>

  <ItemGroup Condition="!Exists('..\swiftpay-api-core\swiftpay-api-core.csproj')">
    <PackageReference Include="swiftpay-api-core" Version="2.15.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="FastEndpoints" Version="7.1.1" />
    <PackageReference Include="JWT" Version="11.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.0.0" />
    <PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.5.4" />
    <PackageReference Include="MiniProfiler.EntityFrameworkCore" Version="4.5.4" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="Resend" Version="0.2.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.10.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates/Email/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
