<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.16" />
    <PackageReference Include="MassTransit" Version="8.5.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.16" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Swiftpay.Api.Gestao\Swiftpay.Api.Gestao.csproj" />
    <ProjectReference Include="..\..\src\Swiftpay.Api.Payment\Swiftpay.Api.Payment.csproj" />
  </ItemGroup>

</Project>
