name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: 169.58.70.201
          username: root
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /root/swiftpay/swiftpay-api
            git pull
            docker compose --env-file .env.production -f docker-compose.production.yaml up -d --build
            docker image prune -f
